name: build inputs mapping action
concurrency:
  group: fetch-vars-action
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-fetch-vars-action.yaml
      - fetch-vars/src/**/*
      - fetch-vars/package*.json
      - fetch-vars/*.js

permissions:
  contents: write

env:
  AUTHOR_EMAIL: admin+github-actions@tapclap.com
  AUTHOR_NAME: 'Github Actions'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 20

      - name: node modules
        working-directory: fetch-vars
        run: npm ci

      - name: build
        working-directory: fetch-vars
        run: npm run build


      - name: commit builded action
        run: |
          if git status | grep 'fetch-vars/dist/' -q;
          then
            git config --global user.email "${AUTHOR_EMAIL}"
            git config --global user.name "${AUTHOR_NAME}"
            git add ./fetch-vars/dist
            git commit -m "builded fetch-vars action"
            while true; do
              if ! git push origin ${{ github.ref }}:${{ github.ref }}; then
                echo "Push failed, sleep 10 seconds and retrying..."
                git pull --rebase
                sleep 10
                continue
              else
                break
              fi
            done
          fi